### ISSUE TITLE
Rose - Armazem das Fábricas LEMBRAR LUCAS

### ISSUE THREAD

**Issue by ruangervasi** [ruangervasi/support#24]
Relatório de venda no NFC e mostrar os cancelados...

**Comment by ruangervasi** [comment]
Lucas está verificando

**Comment by lucasselliach** [comment]
Lucas está verificando... pode deixar...

**Comment by ruangervasi** [comment]
E aí Lucas que estava verificando, alguma posição sobre isso? No aguardo.

**Comment by ruangervasi** [comment]
Lucas disse que está ok, closing issue.
