### ISSUE TITLE
Verificar erro no Sintegra da Casa das Ervas 3349-3515

### ISSUE THREAD

**Issue by ruangervasi** [ruangervasi/support#33]
Transferindo banco para o Lucas

**Comment by lucasselliach** [comment]
ta ae o script 

UPDATE ecfCasaDasErvas.reg05
LEFT JOIN gsnCasaDasErvas.orcamento ON ecfCasaDasErvas.reg05.CodigoProd = gsnCasaDasErvas.orcamento.codigo
SET ecfCasaDasErvas.reg05.Quantidade = gsnCasaDasErvas.orcamento.quantidade
WHERE gsnCasaDasErvas.orcamento.nrcupomecfpaf = ecfCasaDasErvas.reg05.COO
AND ecfCasaDasErvas.reg05.Quantidade = 0 AND ecfCasaDasErvas.reg05.COO = xxxxx

**Comment by ruangervasi** [comment]
Lucas...

**Comment by ruangervasi** [comment]
Comandos utilizados com o Lucas que funcionaram corretamente para a loja 1, pode ser executado em qualquer loja em que o banco ECF esteja na mesma maquina que o GSN:

UPDATE ecf.reg05
LEFT JOIN gsn.orcamento ON ecf.reg05.CodigoProd = gsn.orcamento.codigo
SET ecf.reg05.Quantidade = gsn.orcamento.quantidade
WHERE gsn.orcamento.nrcupomecfpaf = ecf.reg05.COO
AND ecf.reg05.Quantidade = 0; 

UPDATE gsn.reg05
LEFT JOIN gsn.orcamento ON gsn.reg05.CodigoProd = gsn.orcamento.codigo
SET gsn.reg05.Quantidade = gsn.orcamento.quantidade
WHERE gsn.orcamento.nrcupomecfpaf = gsn.reg05.COO
AND gsn.reg05.Quantidade = 0;

**Comment by ruangervasi** [comment]
Os 2 comandos acima devem apresentar a mesma quantidade de registros alterados.
