### ISSUE TITLE
Arrumar zebra em PONTO CERTO MOVÉIS E ELETRO

### ISSUE THREAD

**Issue by lucasselliach** [ruangervasi/support#36]
SÃO JOÃO BATISTA
07.059.265/0004-57
(48) 3265-5915

FALAR COM VANESSA

-> ODBC não configurado para lojas

**Comment by ruangervasi** [comment]
Ok.

**Comment by Pierry** [comment]
Arrumar zebra? kkkkkkkk

**Comment by ruangervasi** [comment]
Liguei ninguém atendeu, ligarei mais tarde.

**Comment by ruangervasi** [comment]
Liguei novamente, sem êxito.

**Comment by ruangervasi** [comment]
Novamente liguei, nada.

**Comment by ruangervasi** [comment]
Resolvido via acesso remoto.

instalei e configurei o Hamachi e configurei as conexões com as outras lojas com base no ODBC.ini do servidor...
